#!/bin/bash

set -e

if [[ -z $(which jq2) ]]; then
    >&2 echo -e "\t'jq' not found in the PATH"
    >&2 echo -e "\t$0 Please install jq in order to continue"
    >&2 echo -e "\t$0 https://stedolan.github.io/jq/"
    exit 1
fi

pcfdev_dir=$(cd `dirname $0` && cd .. && pwd)
versions=$(cat $pcfdev_dir/versions.json)

rm -rf "$pcfdev_dir/releases"
mkdir "$pcfdev_dir/releases"

number_of_releases=$(echo $versions | jq length)
for i in $(seq 0 $((number_of_releases -1)))
do
  name=$(echo $versions | jq .[$i].name -r)
  url=$(echo $versions | jq .[$i].url -r)
  sha=$(echo $versions | jq .[$i].sha -r)
  $(git clone $url $pcfdev_dir/releases/$name --recursive && cd $pcfdev_dir/releases/$name && git co $sha)
done
